[package]
name = "kyexyz/bloxios"
description = "Roblox Http Client"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@^4"
TableUtil = "sleitnick/table-util@^1"
Signal = "sleitnick/signal@1.1.0"
Janitor = "howmanysmall/janitor@^1.14.1"
